package com.laleetaprojjects.main.entity;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import com.fasterxml.jackson.annotation.JsonBackReference;

@Entity
public class SkillInfo {
	@Id
	@GeneratedValue
	private long skillId;
	private String skillName;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fid", referencedColumnName = "fresherId")
	// fresherId in FresherInfo autogenerated variable name..................

	private FresherInfo fresherinfo;

	public SkillInfo(String skillName) {

		this.skillName = skillName;

	}

	public long getFresherinfo() {
		return fresherinfo.getFresherId();
	}

	public void setFresherinfo(FresherInfo fresherinfo) {
		this.fresherinfo = fresherinfo;
	}

	public SkillInfo() {

	}

	public long getSkillId() {
		return skillId;
	}

	public void setSkillId(long skillId) {
		this.skillId = skillId;
	}

	public String getSkillName() {
		return skillName;
	}

	public void setSkillName(String skillName) {
		this.skillName = skillName;
	}

}
